### ISSUE TITLE
[Bug] Does not build on Windows

### ISSUE THREAD

**Issue by cretz** [temporalio/ui-server#104]
### What are you really trying to do?

Build on Windows.

### Describe the bug

Recursively cloning and running `go build ./cmd/server` gives:

    server\server.go:52:12: pattern generated/ui/_app/assets/pages/namespaces/\[namespace\]/workflows/\[workflow\]/\[run\]/_*: syntax error in pattern

This works on Linux just fine (well, you need to specify `-o server-binary` or something because the cmd package name is the same as an existing dir name unfortunately).

It makes sense if the project wants to stick with `make` and does not work well outside of Windows, but the Go server should at least build and/or run unit tests. This causes problems for projects like Temporalite which have embedded this project and now can't build on Windows.

I haven't investigated why this compile error occurs on Windows only. Just opening this issue to track it.

**Comment by feedmeapples** [comment]
seems upgrading to go v1.18 will address this issue? https://github.com/temporalio/ui-server/pull/86

release notes mention they are targeting for Feb to release the offiical version. Could be in March https://tip.golang.org/doc/go1.18

**Comment by cretz** [comment]
:+1: I think this issue should remain open until we at least mention Go 1.18 is required for Windows.

In the meantime, we might want to either add both macOS and Windows as CI targets, or clearly say they are not supported.

**Comment by feedmeapples** [comment]
@cretz go 1.18 was released, https://github.com/temporalio/ui-server/pull/86 is merged

Added another PR to test the build on Windows and MacOS https://github.com/temporalio/ui-server/pull/115

**Comment by feedmeapples** [comment]
Windows build still fails https://github.com/temporalio/ui-server/runs/5578250635?check_suite_focus=true

**Comment by jlegrone** [comment]
FYI after https://github.com/DataDog/temporalite/pull/66 Temporalite builds on Windows with ui-server enabled: https://github.com/DataDog/temporalite/runs/6336627938?check_suite_focus=true

**Comment by robholland** [comment]
Now building on OS X and Windows.
