### ISSUE TITLE
[Bug] After oauth, redirect to web UI

### ISSUE THREAD

**Issue by lorensr** [temporalio/ui-server#134]
Not sure if this is fixed here or in Auth0 settings, but after these steps:

- Visit `https://web.loren.temporal-dev.tmprl.cloud/signin`
- Click "Continue to SSO"
- Select which Google account (`loren@temporal.io`)

I'm taken to `https://myaccount.google.com/`

**Comment by feedmeapples** [comment]
this was addressed in recent versions, i'll keep the ticket open until the most recent version is published to cloud

**Comment by feedmeapples** [comment]
https://github.com/temporalio/ui-server/pull/122

**Comment by stevekinney** [comment]
@feedmeapples We might want to double check. It was definitely present when @lorensr and I were pairing the other day and I don't think Loren was using a particularly old version, but maybe it shipped in v0.9.0, which shipped the morning before?

**Comment by feedmeapples** [comment]
fixed in versions v0.10.1+
