### ISSUE TITLE
[Feature Request] Setting for Disabling Write Permissions

### ISSUE THREAD

**Issue by stevekinney** [temporalio/ui-server#135]
### Is your feature request related to a problem? Please describe.

Users would like to disable certain actions (e.g. terminating a workflow) and put the UI into a full read-only mode.

### Describe the solution you'd like

We can do this on the client (see temporalio/ui#425), but we should also disable this from the web server as well.

**Comment by feedmeapples** [comment]
added in https://github.com/temporalio/ui-server/pull/194
