### ISSUE TITLE
[Bug] v2 UI Fails to run as NonRootUser

### ISSUE THREAD

**Issue by kingster** [temporalio/ui-server#156]
### What are you really trying to do?

Our Production cluster has a requirement that all images must be run as  non-root user. While the previous temporalio/web used to run as non-root user  the v2 image fails to run as non-root user. 

### Describe the bug
 
When running as non-root user the docker-image throws this error

```
unable to create open ./config/docker.yaml: permission denied
```

### Minimal Reproduction

Add  in web-deployment.yaml 

```
  securityContext:
            runAsNonRoot: true
            runAsUser: 1000 #temporal user
```

### Environment/Versions
 
- OS and processor: [e.g. M1 Mac, x86 Windows, Linux]
- Temporal Version: 1.16.2
- Temporal UI : 2.0.1
- Are you using Docker or Kubernetes or building Temporal from source? : Kubernetes, using offical images.

 ### Additional Info

Temporalio/web Image has an addUser with uid=1000
![image](https://user-images.githubusercontent.com/709368/173322313-d5e6557c-3098-4cea-8746-3a521b0f088f.png)

temporalio/ui doesn't have any non-root user configured.
![image](https://user-images.githubusercontent.com/709368/173322440-c5f5ef65-1a83-4b1e-904c-228c5a0b5675.png)

**Comment by fortisitpl** [comment]
fix:

RUN addgroup -g 5000 temporal
RUN adduser -u 5000 -G temporal -D temporal

COPY --from=ui-builder /home/ui-builder/ui-server ./
COPY docker/start-ui-server.sh ./start-ui-server.sh
COPY docker/config_template.yaml ./config/config_template.yaml


RUN chown temporal:temporal /home/ui-server -R
