### ISSUE TITLE
[Bug] unable to set user: securecookie: the value is too long

### ISSUE THREAD

**Issue by jmcnevin** [temporalio/ui-server#181]
### What are you really trying to do?

Trying to use v2.2.1 with our SSO system.

### Describe the bug

Our OIDC SSO system returns JWTs that may be very large.  That seems to make this cookie handler angry.

### Minimal Reproduction

SSO provider must provide JWT that contains a large number of claims.  `/auth/sso/callback` returns a 500 code with this message in the logs: `code=500, message=unable to set user: securecookie: the value is too long`

**Comment by feedmeapples** [comment]
there is now an option to switch to filesystem for storing session data. It's currently an opt-in https://github.com/temporalio/ui-server/blob/9c9a5d5731e5ed7e6dba67509ff50a4210621719/docker/config_template.yaml#L45
