### ISSUE TITLE
[Bug] Relative paths

### ISSUE THREAD

**Issue by cv65kr** [temporalio/ui-server#224]
### Describe the bug

https://github.com/temporalio/ui-server/blob/fe53a7c6c64404df7f290a5dd09df475fc28a265/server/generated/ui/index.html#L7

New docker image `temporalio/ui:2.6.0` contains relative paths and that's generate issue like css/js not found etc.
Instead of 
https://temporal.workflow.local/namespaces/default/workflows/1663233135/452a09d9-227f-4711-8495-88ca1f342ac7/history/css/normalize.css

it should be 
https://temporal.workflow.local/css/normalize.css

**Comment by feedmeapples** [comment]
related issue https://github.com/sveltejs/kit/issues/6767

Reproes when navigating to the UI by any non-root URL (ie http://localhost:8080/namespaces/ and not http://localhost:8080)

**Comment by feedmeapples** [comment]
was addressed in https://github.com/temporalio/ui/pull/836

+ a note in v2.6.1 release https://github.com/temporalio/ui-server/releases/tag/v2.6.1
