### ISSUE TITLE
[Bug] Public Path doesn't process values passed with quotes

### ISSUE THREAD

**Issue by feedmeapples** [temporalio/ui-server#230]
### Describe the bug

`TEMPORAL_PUBLIC_PATH` works only when the value is passed plain w/o the quotes

### Minimal Reproduction

Build an image following these steps https://github.com/temporalio/ui-server/tree/main/docker#serve-ui-under-a-sub-path

Except for setting public path as `TEMPORAL_PUBLIC_PATH="/custom-path"`

### Environment/Versions

- OS and processor: [e.g. M1 Mac, x86 Windows, Linux]
- Temporal Version: [e.g. 1.14.0?] and/or SDK version
- Are you using Docker or Kubernetes or building Temporal from source?

**Comment by robholland** [comment]
That's not a bug in ui-server, it's a shell issue. Users should either quote the whole shell `word` or not use quotes at all. `TEMPORAL_PUBLIC_PATH=foo` or if quotes are needed `"TEMPORAL_PUBLIC_PATH=foo"`.
