### ISSUE TITLE
[Bug] v2.6.2 image in dockerhub contains v2.6.1 binary

### ISSUE THREAD

**Issue by yolken-airplane** [temporalio/ui-server#234]
### What are you really trying to do?

Run the latest version of the ui via Docker.

### Describe the bug

It appears that the 2.6.2 image contains a 2.6.1 binary? We noticed this when we tried to upgrade but still got a "[📥 Temporal UI v2.6.2 is available](https://github.com/temporalio/ui-server/releases/tag/v2.6.2)" banner in the UI.

### Minimal Reproduction

```
Benjamin-Yolkens-MacBook-Pro:lib benjaminyolken$ docker pull temporalio/ui:2.6.2
2.6.2: Pulling from temporalio/ui
Digest: sha256:3e01bb69fd1a4b381f13eb62400e49b30f79bc32798598d3a7b5f37d38829d03
Status: Image is up to date for temporalio/ui:2.6.2
docker.io/temporalio/ui:2.6.2
Benjamin-Yolkens-MacBook-Pro:lib benjaminyolken$ docker run -ti --rm --entrypoint=/bin/bash temporalio/ui:2.6.2 '-c' './ui-server -v'
Temporal UI version 2.6.1
```

### Environment/Versions

N/A

### Additional context

N/A

**Comment by feedmeapples** [comment]
the image didn't include [the v2.6.2 version bump commit](https://github.com/temporalio/ui-server/commit/5d0a35813295c24382168df9147d99a694f963cc) so it prints the wrong version. It still includes all the features from v2.6.2

**Comment by feedmeapples** [comment]
releasing v2.7.0 with the correct reported version

**Comment by yolken-airplane** [comment]
> releasing v2.7.0 with the correct reported version

Great, thank you!
