### ISSUE TITLE
[Bug] Missing TEMPORAL_UI_PORT results in invalid config generation in k8s.

### ISSUE THREAD

**Issue by shanna** [temporalio/ui-server#236]
### What are you really trying to do?

Run `temporalio/ui` image in k8s.

### Describe the bug

It's a minor thing but running `temporalio/ui:2.6.2` in k8s without setting `TEMPORAL_UI_PORT` environment variable results in invalid config in the generated `config/docker.yaml` at least on docker-desktop (Windows WSL2):

```
2022/10/09 20:49:38 Loading config; env=docker,configDir=config
2022/10/09 20:49:38 Loading config files=[config/docker.yaml]
config file corrupted: yaml: unmarshal errors:
  line 2: cannot unmarshal !!str `tcp://1...` into int
```

Looking at the yaml a complete tcp URI `tcp://127.0.0.1:8080` is generated as the value instead of just the port number expected by the UI config. 

### Minimal Reproduction

Create a k8s deployment and don't specify a TEMPORAL_UI_PORT environment variable.

### Environment/Versions

- amd64 Windows
- temporalio/ui:2.6.2 (and 2.6.1)

### Additional context

Running `docker run -it --rm temporalio/ui:2.6.2 bash` and executing `dockerize -template ./config/config_template.yaml:./config/docker.yaml` directly doesn't produce the error. I could only replicate it when the container is run by k8s.

**Comment by ricochet1k** [comment]
Kuternetes creates env variables for services automatically, so you probably have a K8s service named `temporal-ui` which is getting inserted as an environment variable as `TEMPORAL_UI_PORT`.

**Comment by robholland** [comment]
This is indeed due to k8s behaviour. You can fix this using `enableServiceLinks: false`: https://github.com/temporalio/docker-compose/blob/main/k8s/temporal.yaml#L147
