### ISSUE TITLE
TEMPORAL_ADDRESS cannot be set to ipv6

### ISSUE THREAD

**Issue by nivekuil** [temporalio/ui-server#255]
### Describe the bug

TEMPORAL_ADDRESS cannot be set to ipv6

### Minimal Reproduction
```
podman run -e TEMPORAL_ADDRESS='[::1]:7233' docker.io/temporalio/ui:2.8.3
2022/11/19 02:55:33 Loading config; env=docker,configDir=config
2022/11/19 02:55:33 Loading config files=[config/docker.yaml]
config file corrupted: yaml: did not find expected node content

```

### Environment/Versions

- OS and processor: [e.g. M1 Mac, x86 Windows, Linux]
- Temporal Version: [e.g. 1.14.0?] and/or SDK version
- Are you using Docker or Kubernetes or building Temporal from source?

**Comment by nivekuil** [comment]
workaround is to add quotes around it

**Comment by robholland** [comment]
This is because the parser used for environment variables expects yaml, and `[` is not valid when a string is expected, yaml parser assumes that will be an array. Quoting it tells the parser it is a string. This is not something we're likely to fix as there is a workaround.
