### ISSUE TITLE
[Bug] missing csrf token when serving temporal ui under a sub path

### ISSUE THREAD

**Issue by diddowill** [temporalio/ui-server#261]
### Describe the bug
Error happens when we try to "Terminate" a workflow on the UI. 
The error message is:
"missing csrf token in request header"

### Minimal Reproduction

1. build an image following the directions here: https://github.com/temporalio/ui-server/tree/main/docker#serve-ui-under-a-sub-path
2. start the temporal ui server
3. visit the ui page
4. select a running workflow, go to its details, click the "Terminate" button
5. the termination would fail with  a message: "missing csrf token in request header".

### Environment/Versions

- OS and processor: [e.g. M1 Mac, x86 Windows, Linux]
- Temporal Version: [e.g. 1.14.0?] and/or SDK version
- Are you using Docker or Kubernetes or building Temporal from source?

**Comment by feedmeapples** [comment]
still not able to repro the issue using via both HTTP and HTTPS

Do your UI and API URLs match? ie:
![image](https://user-images.githubusercontent.com/11838981/208831238-507c1f5d-b5a4-4865-bdd1-84479723b43c.png)
 
 What version of the UI you are running?

**Comment by feedmeapples** [comment]
Actually is your Auth enabled? testing with auth disabled as then CSRF token is checked

**Comment by feedmeapples** [comment]
still no repro on v2.9.1. What is your UI version?

**Comment by diddowill** [comment]
@feedmeapples 
I think the UI version should be 2.8.x。I built it from master branch when the official release is 2.8.
Auth enabled? No, I did not set such a setting, and I visit the UI without login.
The API url is correct: with the sub path. 
What's more, If I forward the web ui service from remote machine to my local machine, and visit the ui from localhost:8080/my-sub-path, then it works.

**Comment by feedmeapples** [comment]
any chance you could try the same on v2.9.1? as i couldn't repro the issue on this version and there have been some recent changes in CSRF/auth processing

**Comment by feedmeapples** [comment]
afaik this could be an issue on older versions of the UI, however as of the latest version couldn't repro. Closing unless there is a response
