### ISSUE TITLE
[Feature Request] Allow serving CSRF cookie over HTTP (w/o TLS)

### ISSUE THREAD

**Issue by yousseftelda** [temporalio/ui-server#281]
### Is your feature request related to a problem?
Yes

### Problem description
We serve temporal UI over https://tailscale.com. Tailscale uses WireGuard to encrypt the connection, i.e the connection is secure. However, the browser is unware of the existence of WireGuard, and considers the connection to temporal UI to be insecure as it is served over HTTP, which prevents the CSRF token from being set due to this configuration: https://github.com/temporalio/ui-server/blob/529addb76f8247ecbf0b2d9a5bfee8f4bda95a5f/server/server.go#L102

### Describe the solution you'd like
Allow controlling the value of the `CookieSecure` flag for CSRF tokens.

**Comment by stevekinney** [comment]
@robholland Could you look into this? I'd love to support it.

**Comment by yousseftelda** [comment]
Thanks a lot!
